config:
  # Root of the installation tree
  install_tree: /ssoft/spack/paien/v2/opt/spack/

  # Root of the module files
  module_roots:
    tcl: /ssoft/spack/paien/v2/share/spack/modules
    lmod: /ssoft/spack/paien/v2/share/spack/lmod
    dotkit: /ssoft/spack/paien/v2/share/spack/dotkit
